


// import React from "react";
// import { Card, Button, Row, Col } from "react-bootstrap";

// export default function Home() {
//   return (
//     <div className="container-fluid">
//       <h1 className="mb-4">Welcome to Event Management Dashboard 🎉</h1>

//       {/* Stats Cards */}
//       <Row className="mb-4">
//         <Col md={4}>
//           <Card className="shadow-sm">
//             <Card.Body>
//               <Card.Title>Total Events</Card.Title>
//               <Card.Text className="fs-2 fw-bold text-primary">12</Card.Text>
//               <Button variant="outline-primary" size="sm">View Events</Button>
//             </Card.Body>
//           </Card>
//         </Col>

//         <Col md={4}>
//           <Card className="shadow-sm">
//             <Card.Body>
//               <Card.Title>Upcoming Events</Card.Title>
//               <Card.Text className="fs-2 fw-bold text-success">5</Card.Text>
//               <Button variant="outline-success" size="sm">See Schedule</Button>
//             </Card.Body>
//           </Card>
//         </Col>

//         <Col md={4}>
//           <Card className="shadow-sm">
//             <Card.Body>
//               <Card.Title>Employees</Card.Title>
//               <Card.Text className="fs-2 fw-bold text-warning">8</Card.Text>
//               <Button variant="outline-warning" size="sm">Manage Staff</Button>
//             </Card.Body>
//           </Card>
//         </Col>
//       </Row>

//       {/* Recent Activity */}
//       <Card className="shadow-sm mb-4">
//         <Card.Header>Recent Activity</Card.Header>
//         <Card.Body>
//           <ul className="list-group">
//             <li className="list-group-item">✅ John created a new event "Tech Summit 2025"</li>
//             <li className="list-group-item">💳 Payment received via M-Pesa for "Wedding Gala"</li>
//             <li className="list-group-item">📊 Report generated by Admin</li>
//           </ul>
//         </Card.Body>
//       </Card>

//       {/* Quick Actions */}
//       <Row>
//         <Col md={6}>
//           <Card className="shadow-sm">
//             <Card.Body>
//               <Card.Title>Create New Event</Card.Title>
//               <Card.Text>Plan and publish a new event.</Card.Text>
//               <Button variant="primary">Add Event</Button>
//             </Card.Body>
//           </Card>
//         </Col>
//         <Col md={6}>
//           <Card className="shadow-sm">
//             <Card.Body>
//               <Card.Title>Generate Reports</Card.Title>
//               <Card.Text>Generate financial or attendance reports.</Card.Text>
//               <Button variant="secondary">Generate</Button>
//             </Card.Body>
//           </Card>
//         </Col>
//       </Row>
//     </div>
//   );
// }

// src/pages/Home.jsx
// import React, { useContext } from "react";
// import { Card, Row, Col, Button } from "react-bootstrap";
// import { FaCalendarAlt, FaUsers, FaChartBar } from "react-icons/fa";
// import { ThemeContext } from "../layout/Layout";

// export default function Home() {
//   const { theme } = useContext(ThemeContext);

//   const bg = theme === "light" ? "light" : "dark";
//   const text = theme === "light" ? "dark" : "light";
//   const cardBg = theme === "light" ? "white" : "#1e1e1e";
//   const cardText = theme === "light" ? "dark" : "light";

//   return (
//     <div className={`p-4 bg-${bg} text-${text}`} style={{ minHeight: "80vh" }}>
//       {/* Welcome Section */}
//       <h2 className="mb-4">Welcome to EventSystem 🎉</h2>
//       <p className="text-muted mb-4">
//         Manage your events, track reports, and collaborate easily.
//       </p>

//       {/* Quick Stats */}
//       <Row className="mb-4">
//         <Col md={4}>
//           <Card className="shadow-sm text-center" style={{ background: cardBg }}>
//             <Card.Body className={`text-${cardText}`}>
//               <FaCalendarAlt size={30} className="mb-2 text-primary" />
//               <h5>12 Upcoming Events</h5>
//               <p className="text-muted">Stay on top of your schedule.</p>
//             </Card.Body>
//           </Card>
//         </Col>
//         <Col md={4}>
//           <Card className="shadow-sm text-center" style={{ background: cardBg }}>
//             <Card.Body className={`text-${cardText}`}>
//               <FaUsers size={30} className="mb-2 text-success" />
//               <h5>245 Registered Users</h5>
//               <p className="text-muted">Engaged and growing community.</p>
//             </Card.Body>
//           </Card>
//         </Col>
//         <Col md={4}>
//           <Card className="shadow-sm text-center" style={{ background: cardBg }}>
//             <Card.Body className={`text-${cardText}`}>
//               <FaChartBar size={30} className="mb-2 text-warning" />
//               <h5>7 Reports Generated</h5>
//               <p className="text-muted">Monitor your performance.</p>
//             </Card.Body>
//           </Card>
//         </Col>
//       </Row>

//       {/* Recent Events */}
//       <h4 className="mb-3">Recent Events</h4>
//       <Row>
//         <Col md={6}>
//           <Card className="shadow-sm mb-3" style={{ background: cardBg }}>
//             <Card.Body className={`text-${cardText}`}>
//               <h5>Annual Tech Conference</h5>
//               <p className="text-muted">📅 March 15, 2025</p>
//               <Button variant={theme === "light" ? "primary" : "light"} size="sm">
//                 View Details
//               </Button>
//             </Card.Body>
//           </Card>
//         </Col>
//         <Col md={6}>
//           <Card className="shadow-sm mb-3" style={{ background: cardBg }}>
//             <Card.Body className={`text-${cardText}`}>
//               <h5>Community Meetup</h5>
//               <p className="text-muted">📅 March 20, 2025</p>
//               <Button variant={theme === "light" ? "primary" : "light"} size="sm">
//                 View Details
//               </Button>
//             </Card.Body>
//           </Card>
//         </Col>
//       </Row>
//     </div>
//   );
// }



// import React, { useContext } from "react";
// import { Card, Row, Col, Button } from "react-bootstrap";
// import { FaCalendarAlt, FaUsers, FaChartBar } from "react-icons/fa";
// import { ThemeContext } from "../layout/Layout";

// export default function Home() {
//   const { theme } = useContext(ThemeContext);

//   const bg = theme === "light" ? "light" : "dark";
//   const text = theme === "light" ? "dark" : "light";
//   const cardBg = theme === "light" ? "white" : "#1e1e1e";
//   const cardText = theme === "light" ? "dark" : "light";
//   const mutedText = theme === "light" ? "text-muted" : "text-secondary";

//   return (
//     <div className={`p-4 bg-${bg} text-${text}`} style={{ minHeight: "80vh" }}>
//       {/* Welcome Section */}
//       <h2 className="mb-3">Welcome to EventSystem 🎉</h2>
//       <p className={`${mutedText} mb-4`}>
//         Manage your events, track reports, and collaborate easily.
//       </p>

//       {/* Quick Stats */}
//       <Row className="mb-4">
//         <Col md={4}>
//           <Card className="shadow-sm text-center" style={{ background: cardBg }}>
//             <Card.Body className={`text-${cardText}`}>
//               <FaCalendarAlt size={30} className="mb-2 text-primary" />
//               <h5>12 Upcoming Events</h5>
//               <p className={mutedText}>Stay on top of your schedule.</p>
//             </Card.Body>
//           </Card>
//         </Col>
        
//         <Col md={4}>
//           <Card className="shadow-sm text-center" style={{ background: cardBg }}>
//             <Card.Body className={`text-${cardText}`}>
//               <FaUsers size={30} className="mb-2 text-success" />
//               <h5>245 Registered Users</h5>
//               <p className={mutedText}>Engaged and growing community.</p>
//             </Card.Body>
//           </Card>
//         </Col>

//         <Col md={4}>
//           <Card className="shadow-sm text-center" style={{ background: cardBg }}>
//             <Card.Body className={`text-${cardText}`}>
//               <FaChartBar size={30} className="mb-2 text-warning" />
//               <h5>7 Reports Generated</h5>
//               <p className={mutedText}>Monitor your performance.</p>
//             </Card.Body>
//           </Card>
//         </Col>
//       </Row>

//       {/* Recent Events */}
//       <h4 className="mb-3">Recent Events</h4>
//       <Row>
//         <Col md={6}>
//           <Card className="shadow-sm mb-3" style={{ background: cardBg }}>
//             <Card.Body className={`text-${cardText}`}>
//               <h5>Annual Tech Conference</h5>
//               <p className={mutedText}>📅 March 15, 2025</p>
//               <Button
//                 variant={theme === "light" ? "primary" : "light"}
//                 size="sm"
//               >
//                 View Details
//               </Button>
//             </Card.Body>
//           </Card>
//         </Col>
//         <Col md={6}>
//           <Card className="shadow-sm mb-3" style={{ background: cardBg }}>
//             <Card.Body className={`text-${cardText}`}>
//               <h5>Community Meetup</h5>
//               <p className={mutedText}>📅 March 20, 2025</p>
//               <Button
//                 variant={theme === "light" ? "primary" : "light"}
//                 size="sm"
//               >
//                 View Details
//               </Button>
//             </Card.Body>
//           </Card>
//         </Col>
//       </Row>
//     </div>
//   );
// }


import React, { useContext } from "react";
import { Card, Row, Col, Button } from "react-bootstrap";
import { FaCalendarAlt, FaUsers, FaChartBar } from "react-icons/fa";
import { ThemeContext } from "../layout/Layout";

export default function Home() {
  const { theme } = useContext(ThemeContext);

  const bg = theme === "light" ? "light" : "dark";
  const text = theme === "light" ? "dark" : "light";
  const cardBg = theme === "light" ? "white" : "#1e1e1e";
  const cardText = theme === "light" ? "dark" : "light";

  return (
    <div className={`p-4 bg-${bg} text-${text}`} style={{ minHeight: "80vh" }}>
      {/* Welcome Section */}
      <h2 className="mb-4">Welcome to EventSystem 🎉</h2>
      <p className="text-muted mb-4">
        Manage your events, track reports, and collaborate easily.
      </p>

      {/* ✅ Quick Stats */}
      <Row className="mb-4">
        <Col md={4}>
          <Card className="shadow-sm text-center" style={{ background: cardBg }}>
            <Card.Body className={`text-${cardText}`}>
              <FaCalendarAlt size={30} className="mb-2 text-success" />
              <Card.Title>Upcoming Events</Card.Title>
              <Card.Text className="fs-2 fw-bold text-success">5</Card.Text>
              <Button variant="outline-success" size="sm">See Schedule</Button>
            </Card.Body>
          </Card>
        </Col>

        <Col md={4}>
          <Card className="shadow-sm text-center" style={{ background: cardBg }}>
            <Card.Body className={`text-${cardText}`}>
              <FaChartBar size={30} className="mb-2 text-info" />
              <Card.Title>Reports</Card.Title>
              <Card.Text className="fs-2 fw-bold text-info">12</Card.Text>
              <Button variant="outline-info" size="sm">View Reports</Button>
            </Card.Body>
          </Card>
        </Col>

        <Col md={4}>
          <Card className="shadow-sm text-center" style={{ background: cardBg }}>
            <Card.Body className={`text-${cardText}`}>
              <FaUsers size={30} className="mb-2 text-warning" />
              <Card.Title>Employees</Card.Title>
              <Card.Text className="fs-2 fw-bold text-warning">8</Card.Text>
              <Button variant="outline-warning" size="sm">Manage Staff</Button>
            </Card.Body>
          </Card>
        </Col>
      </Row>

      {/* ✅ Recent Events */}
      <h4 className="mb-3">Recent Events</h4>
      <Row>
        <Col md={6}>
          <Card className="shadow-sm mb-3" style={{ background: cardBg }}>
            <Card.Body className={`text-${cardText}`}>
              <h5>Annual Tech Conference</h5>
              <p className="text-muted">📅 March 15, 2025</p>
              <Button variant={theme === "light" ? "primary" : "light"} size="sm">
                View Details
              </Button>
            </Card.Body>
          </Card>
        </Col>

        <Col md={6}>
          <Card className="shadow-sm mb-3" style={{ background: cardBg }}>
            <Card.Body className={`text-${cardText}`}>
              <h5>Community Meetup</h5>
              <p className="text-muted">📅 March 20, 2025</p>
              <Button variant={theme === "light" ? "primary" : "light"} size="sm">
                View Details
              </Button>
            </Card.Body>
          </Card>
        </Col>
      </Row>
    </div>
  );
}

