


import React from "react";
import { Card, Button, Row, Col } from "react-bootstrap";

export default function Home() {
  return (
    <div className="container-fluid">
      <h1 className="mb-4">Welcome to Event Management Dashboard 🎉</h1>

      {/* Stats Cards */}
      <Row className="mb-4">
        <Col md={4}>
          <Card className="shadow-sm">
            <Card.Body>
              <Card.Title>Total Events</Card.Title>
              <Card.Text className="fs-2 fw-bold text-primary">12</Card.Text>
              <Button variant="outline-primary" size="sm">View Events</Button>
            </Card.Body>
          </Card>
        </Col>

        <Col md={4}>
          <Card className="shadow-sm">
            <Card.Body>
              <Card.Title>Upcoming Events</Card.Title>
              <Card.Text className="fs-2 fw-bold text-success">5</Card.Text>
              <Button variant="outline-success" size="sm">See Schedule</Button>
            </Card.Body>
          </Card>
        </Col>

        <Col md={4}>
          <Card className="shadow-sm">
            <Card.Body>
              <Card.Title>Employees</Card.Title>
              <Card.Text className="fs-2 fw-bold text-warning">8</Card.Text>
              <Button variant="outline-warning" size="sm">Manage Staff</Button>
            </Card.Body>
          </Card>
        </Col>
      </Row>

      {/* Recent Activity */}
      <Card className="shadow-sm mb-4">
        <Card.Header>Recent Activity</Card.Header>
        <Card.Body>
          <ul className="list-group">
            <li className="list-group-item">✅ John created a new event "Tech Summit 2025"</li>
            <li className="list-group-item">💳 Payment received via M-Pesa for "Wedding Gala"</li>
            <li className="list-group-item">📊 Report generated by Admin</li>
          </ul>
        </Card.Body>
      </Card>

      {/* Quick Actions */}
      <Row>
        <Col md={6}>
          <Card className="shadow-sm">
            <Card.Body>
              <Card.Title>Create New Event</Card.Title>
              <Card.Text>Plan and publish a new event.</Card.Text>
              <Button variant="primary">Add Event</Button>
            </Card.Body>
          </Card>
        </Col>
        <Col md={6}>
          <Card className="shadow-sm">
            <Card.Body>
              <Card.Title>Generate Reports</Card.Title>
              <Card.Text>Generate financial or attendance reports.</Card.Text>
              <Button variant="secondary">Generate</Button>
            </Card.Body>
          </Card>
        </Col>
      </Row>
    </div>
  );
}
